<a href="https://colab.research.google.com/github/Kotekina/Numpy_Pandas/blob/main/HW_lesson2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Тема “Вычисления с помощью Numpy”

In [1]:
import numpy as np

Задание 1 Импортируйте библиотеку Numpy и дайте ей псевдоним np. Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [2]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])

In [3]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [4]:
a.transpose()

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis = 1, dtype = int)

In [6]:
mean_a

array([2, 8])

Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [9]:
a_new = a.transpose()

In [10]:
mean_a.shape

(2,)

In [11]:
a_new.shape

(5, 2)

In [12]:
a_centered = a_new - mean_a

In [13]:
a_centered

array([[-1, -2],
       [ 0,  0],
       [ 1,  3],
       [ 1,  2],
       [-1, -1]])

Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.


In [14]:
a_centered_sp =  a_centered[:, 0] @ a_centered[:, 1]

In [15]:
a_centered_sp_after = a_centered_sp/(len(a[:,0])-1)

In [16]:
a_centered_sp_after

8.0